title: Hi, I'm Cassie &#128512 # your name (or website title) here
logo: "/images/IMG_7643.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Hi! I'm a Data Analyst with three years experience driving business insights through statistical analysis and interactive visualizations. 
  <br><br>
  Currently, I'm part of Leaf Group's Business Intelligence Team, build complicated data sources in BigQuery and informative dashboards in Tableau for large e-commerce brands including Society6.com, Deny Designs, and Saatchi Art. 
  <br><br>
  Programming: Python, R
  Database: SQL
  <a href="https://www.linkedin.com/in/jy-zng/">View My LinkedIn Profile</a> <br />
  <a href="https://public.tableau.com/profile/cassie.jingyi.zhang#!/?newProfile=&activeTab=0">View My Tableau Public</a> <br />
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
